apiVersion: v1
kind: Namespace
metadata:
  name: efa-validation
  labels:
    purpose: efa-validation
    project: efa-validation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: efa-runner
  namespace: efa-validation
