# -----------------------------------------------------------------------------
# Stage-1 image: nccl-tests built against the common base
# -----------------------------------------------------------------------------
ARG BASE_IMAGE=788668107894.dkr.ecr.us-east-2.amazonaws.com/yanxi/base-cuda-efa:v1
FROM ${BASE_IMAGE}

ARG NCCL_TESTS_VERSION=v2.14.0

RUN git clone --depth 1 -b ${NCCL_TESTS_VERSION} https://github.com/NVIDIA/nccl-tests.git /opt/nccl-tests && \
    cd /opt/nccl-tests && \
    make -j$(nproc) MPI=1 MPI_HOME=/opt/amazon/openmpi \
      NCCL_HOME=/usr/local/cuda \
      CUDA_HOME=/usr/local/cuda

ENV PATH="/opt/nccl-tests/build:${PATH}"

WORKDIR /opt/nccl-tests
CMD ["/bin/bash"]
